spring:
  datasource:
    url: jdbc:postgresql://db:5432/transportadora
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hora em milissegundos
  redis:
    host: redis
    port: 6379
    connect-timeout: 2000 # 2 segundos

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.flywaydb: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8080 